rdr pass on lo0 proto { tcp, udp } from any to any port 53 -> 127.0.0.1 port 5354
rdr pass on en0 proto { tcp, udp } from any to any port 53 -> 127.0.0.1 port 5354
pass out quick proto { tcp, udp } from any to 10.54.68.68 port 53
pass out quick proto { tcp, udp } from any to 10.54.129.129 port 53
pass out quick proto { tcp, udp } from any to 1.1.1.1 port 53
pass out quick proto { tcp, udp } from any to 8.8.8.8 port 53
